### ISSUE TITLE
Everyone are using vortex command or serverinfo command

### ISSUE THREAD

**Issue by THECOBRAMAN** [jagrosh/Vortex#100]
Hey sir my issue is that everyone are using and serverinfo with vortex prefix and vortex is accepting this command and giving the serverinfo. I don't want anyone to use any of the vortex command in any of the channel please see my issue and solve it and tell me the solution of it sir.

**Comment by jagrosh** [comment]
This is intentional behavior of the bot; all the info in those commands is public information that users can look up in many ways, so it is reasonable to expect that they can use the command to view that information. All Vortex commands use Discord's permissions to determine what users can and can't do.
