### ISSUE TITLE
URLResolver doesn't exist

### ISSUE THREAD

**Issue by okx-code** [jagrosh/Vortex#34]
In AutoMod.java, there is no class called "URLResolver", but is is referenced in the code. The only `*` import in that class is `net.dv8tion.jda.core.entities.*`, and `net.dv8tion.jda.core.entities.URLResolver` doesn't exist. It also doesn't exist in the same package.

**Comment by jagrosh** [comment]
The code in this repository exists for users of the bot to be able to understand how it works, and for other developers to see how certain problems were tackled. It is not intended to be self-hostable, so if you wish to compile and run it yourself, you will need to implement those classes on your own or make sufficient edits so that those classes are not required.
