### ISSUE TITLE
AvatarUtil doesn't exist

### ISSUE THREAD

**Issue by okx-code** [jagrosh/Vortex#35]
In the BasicLogger class, it imports `com.jagrosh.vortex.utils.AvatarUtil`, but that class does not exist: https://github.com/jagrosh/Vortex/tree/master/src/main/java/com/jagrosh/vortex/utils

**Comment by jagrosh** [comment]
The code in this repository exists for users of the bot to be able to understand how it works, and for other developers to see how certain problems were tackled. It is not intended to be self-hostable, so if you wish to compile and run it yourself, you will need to implement those classes on your own or make sufficient edits so that those classes are not required.

**Comment by okx-code** [comment]
Well, I was intending to improve the code and make a PR.
