### ISSUE TITLE
Automod Capabilities

### ISSUE THREAD

**Issue by Willersmunk** [jagrosh/Vortex#46]
Howdy! On a server I moderate in, we've been trying to setup Vortex and came across a small thing that could be added that would make Vortex sublime: Automod capabilities to pardon after a set time period. The team I work with have to rely upon Dyno for this and it's kinda inconvenient considering Vortex does everything else, and does it much better. Please consider adding this feature to Vortex.

- Willersmunk

**Comment by jagrosh** [comment]
This probably won't be added; the concept of strikes is to keep a permanent record of infractions. Also, _having strikes_ doesn't have any negative impacts to a user, only _receiving new strikes_ does, so even if a user already has strikes, they won't see any negative effects unless they break a rule again. Vortex is primarily designed such that pardoning strikes is unnecessary except when strikes are given accidentally, or for false-positive moderation. I would recommend changing your server's punishments if you want each strike to be less impactful. For example, instead of:
```
2 - Mute 10m
3 - Kick
4 - Ban
```
You could do something like
```
2 - Mute 5m
3 - Mute 10m
4 - Mute 2h
5 - Mute 1d
6 - Ban 1d
7 - Ban 2d
8 - Ban 7d
9 - Ban
```
which would enable users to get more strikes over time but still have increasingly worse punishments. If this doesn't suit your needs, then my best advice would be to seek out a bot that is geared towards temporary strikes instead of permanent ones.

**Comment by Willersmunk** [comment]
Sorry, I just saw your response. Thanks for commenting, I'll speak with my team and see what we can do. I definitely understand, after reading, how Vortex is meant to be used and will keep that in mind for the future.

Again, big thanks
