### ISSUE TITLE
add ability to disable message edit logs while keeping message deletion logs

### ISSUE THREAD

**Issue by xxfoofyxx** [jagrosh/Vortex#62]
i think this would be a good feature for enhancing privacy, e.g. someone meant to paste a funny meme, but instead pasted their account password, then edited the message to change it. now their account password is logged in the servers most likely public log channel, and the only way to remove it would to be contacting an admin (which could take some time)

i'd add enhancement label, but idk how to use labels on github lol

**Comment by jagrosh** [comment]
In regards to the specific situation you've described: Generally, it is poor practice to make message logs public. Secondly, this doesn't solve the presented problem, as deleting the message (as most people would do if they accidentally sent a password) would still get logged. Finally, since most Discord servers are public and selfbots run rampant, it is very likely that several people are already logging everything that gets posted, so the best practice in a case like this is to change your password.

Regardless of the specific situation you've described, I don't think that I will add this feature, as edited and deleted messages go hand-in-hand in providing the full history of a message.
