### ISSUE TITLE
Add a >>bans command that has the ability to show recent bans and search for members on the ban list

### ISSUE THREAD

**Issue by NicholasK516** [jagrosh/Vortex#73]
This would be much like the >>audit command, showing recent bans. If you do >>bans search Vortex would search for a member matching the specified name and would do a search for a specified ban reason. Example: **>>bans search member jagrosh**  **>>bans search reason trolling**. If you do >>bans all it will show the full ban list, reason, and moderator(if possible). The permissions to use this command would be Ban Members or the Moderator Role.

**Comment by crckhub** [comment]
I really like this!
Maybe extend this and also add >>kicks, >>mutes, >>automods.
The latter would show the most recent actions performed by the automoderation

**Comment by novialriptide** [comment]
Hello, I would like to work on this issue.

**Comment by andrewhong04** [comment]
Due to the hostile responses I've received from the Discord server, I don't think I want to work on this issue anymore.

**Comment by Sanduhr32** [comment]
@novialriptide dude... thats how open source contributing works.

**Comment by MichailiK** [comment]
Since bans are now paginated on the API, this is more difficult to implement, especially because of rate limits.

> Hello, I would like to work on this issue

In most, primarily small, git repositories, anything is up-for-grabs. This is a small & somewhat inactive repository, so fiddling around with assignments and such, is a waste of time for the (already busy) maintainer.

You can work on any feature you want. It will eventually get reviewed by the maintainer and/or contributors. Then, once all issues are resolved, it will likely be merged.

Take a look at [my pull requests](https://github.com/jagrosh/Vortex/pulls?q=is%3Apr+author%3AMichailiK) as an example.

**Comment by novialriptide** [comment]
> @novialriptide dude... thats how open source contributing works.

@Sanduhr32 Isn't open source contributing all about volunteers looking for work to do?

> You can work on any feature you want. It will eventually get reviewed by the maintainer and/or contributors. Then, once all issues are resolved, it will likely be merged.

@MichailiK Thanks for the reply, but looking at the active community on jagrosh's Discord server, I don't think it's worth any effort working on this Discord bot.

**Comment by Sanduhr32** [comment]
If you are a volunteer and are looking for work, you would just see if the project has an open issue & try to solve it imo.

That's the thing about open source volunteers.
They come and go, they do stuff if they like, but they mustn't. They don't have to ask what they should do or whether they should do it (unless the project has proper planing & several volunteers & todos)

**Comment by novialriptide** [comment]
Hey @NicholasK516, sorry for the drama I've started up. You can reopen this issue in case another programmer happens to stumble upon this.
